<?php

return [

    'Bae' => [
        'Bacin',
        'Bae',
        'Dersalam',
        'Gondangmanis',
        'Karangbener',
        'Ngembalrejo',
        'Panjang',
        'Pedawang',
        'Peganjaran',
        'Purworejo',
    ],

    'Dawe' => [
        'Cendono',
        'Colo',
        'Cranggang',
        'Dukuhwaringin',
        'Glagah Kulon',
        'Japan',
        'Kajar',
        'Kandangmas',
        'Kuwukan',
        'Lau',
        'Margorejo',
        'Piji',
        'Puyoh',
        'Rejosari',
        'Samirejo',
        'Soco',
        'Tergo',
        'Ternadi',
    ],

    'Gebog' => [
        'Besito',
        'Getasrabi',
        'Gondosari',
        'Gribig',
        'Jurang',
        'Karangmalang',
        'Kedungsari',
        'Klumpit',
        'Menawan',
        'Padurenan',
        'Rahtawu',
    ],

    'Jati' => [
        'Getaspejaten',
        'Jati Kulon',
        'Jati Wetan',
        'Jepangpakis',
        'Jetiskapuan',
        'Loram Kulon',
        'Loram Wetan',
        'Megawon',
        'Ngembal Kulon',
        'Pasuruhan Kidul',
        'Pasuruhan Lor',
        'Ploso',
        'Tanjungkarang',
        'Tumpangkrasak',
    ],

    'Jekulo' => [
        'Bulung Kulon',
        'Bulungcangkring',
        'Gondoharum',
        'Hadipolo',
        'Honggosoco',
        'Jekulo',
        'Klaling',
        'Pladen',
        'Sadang',
        'Sidomulyo',
        'Tanjungrejo',
        'Terban',
    ],

    'Kaliwungu' => [
        'Bakalankrapyak',
        'Banget',
        'Blimbing Kidul',
        'Ggamong',
        'Garung Kidul',
        'Garung Lor',
        'Kaliwungu',
        'Karangampel',
        'Kedungdowo',
        'Mijen',
        'Papringan',
        'Prambatan Kidul',
        'Prambatan Lor',
        'Setrokalangan',
        'Sidorekso',
    ],

    'Kudus' => [
        // Desa
        'Barongan',
        'Burikan',
        'Damaran',
        'Demaan',
        'Demangan',
        'Glantengan',
        'Janggalan',
        'Kaliputu',
        'Kauman',
        'Krandon',
        'Langgardalem',
        'Mlati Lor',
        'Nganguk',
        'Rendeng',
        'Singocandi',
        'Kramat',

        // Kelurahan
        'Kajeksan',
        'Kerjasan',
        'Mlati Kidul',
        'Mlati Norowito',
        'Panjunan',
        'Purwosari',
        'Sunggingan',
        'Wergu Kulon',
        'Wergu Wetan',
    ],

    'Mejobo' => [
        'Golantepus',
        'Gulang',
        'Hadiwarno',
        'Jepang',
        'Jojo',
        'Kesambi',
        'Kirig',
        'Mejobo',
        'Payaman',
        'Temulus',
        'Tenggeles',
    ],

    'Undaan' => [
        'Glagahwaru',
        'Kalirejo',
        'Karangrowo',
        'Kutuk',
        'Lambangan',
        'Larikrejo',
        'Medini',
        'Ngemplak',
        'Sambung',
        'Terangmas',
        'Undaan Kidul',
        'Undaan Lor',
        'Undaan Tengah',
        'Wates',
        'Wonosoco',
        'Berugenjang',
    ],

];
